---

- name: Fail when credentials are not present
  fail: msg="AWS credentials must be defined (starbound_aws_access_key/starbound_aws_secret_key)"
  when: item is undefined
  with_items:
    - "{{ starbound_aws_access_key }}"
    - "{{ starbound_aws_secret_key }}"

- name: Fail when S3 bucket name is not present
  fail: msg="AWS S3 bucket name must be defined (starbound_backup_s3_bucket)"
  when: starbound_backup_s3_bucket is undefined

- name: Ensure Starbound is stopped
  service:
    name: starbound
    state: stopped
  become_user: steam

- name: Compress universe folder
  shell: zip -r universe.zip universe
  args:
    chdir: /home/steam/starbound/storage

- name: Backup universe to S3
  s3:
    mode: put
    src: /home/steam/starbound/storage/universe.zip
    object: universe.zip
    bucket: "{{ starbound_backup_s3_bucket }}"
    aws_access_key: "{{ starbound_aws_access_key }}"
    aws_secret_key: "{{ starbound_aws_secret_key }}"

- name: Ensure universe archive is removed
  file:
    path: /home/steam/starbound/storage/universe.zip
    state: absent
  
- name: Ensure Starbound is started
  service:
    name: starbound
    state: started
  become_user: steam