---

- name: Fail when credentials are not present
  fail: msg="Steam credentials must be defined (starbound_steam_user/starbound_steam_pass)"
  when: item is undefined
  with_items:
    - "{{ starbound_steam_user }}"
    - "{{ starbound_steam_pass }}"

- name: Ensure apt cache is up to up-to-date
  apt:
    update_cache: yes

- name: Ensure required packages are installed
  apt:
    name: "{{ item }}"
  with_items:
    - lib32gcc1
    - libvorbisfile3
    - python-pip
    - zip

- name: Ensure required Python packages are installed
  pip:
    name: "{{ item }}"
  with_items:
    - boto

- name: create steam user
  user:
    name: steam
  register: fresh_install

- name: Ensure steamcmd directory exists
  file:
    path: /home/steam/steamcmd
    state: directory
    owner: steam

- name: Ensure steamcmd is present
  get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: /home/steam/steamcmd
    owner: steam

- name: Ensure steamcmd is extracted
  unarchive:
    copy: no
    src: /home/steam/steamcmd/steamcmd_linux.tar.gz
    dest: /home/steam/steamcmd
    owner: steam
    creates: /home/steam/steamcmd/steamcmd.sh

- name: Ensure Starbound is installed. Update if starbound_update variable is set.
  shell: "/home/steam/steamcmd/steamcmd.sh +login {{ starbound_steam_user }} {{ starbound_steam_pass }} +force_install_dir ../starbound +app_update 211820 +quit"
  become_user: steam
  become: yes
  when: starbound_update or fresh_install.changed

- name: Ensure custom configuration is loaded
  copy:
    src: "{{ starbound_server_config_file }}"
    dest: /home/steam/starbound/storage/starbound_server.config
    owner: steam
  register: server_config

- name: Ensure Starbound is installed as a service
  template: 
    src: starbound.j2
    dest: /etc/init.d/starbound
    mode: 0777
    owner: steam
  register: service_script

- name: Ensure Starbound is restarted if configuration or service script changed
  service:
    name: starbound
    state: restarted
  become_user: steam
  when: server_config.changed or service_script.changed

- name: Ensure that the universe is backed up if the backup variable is set
  include: backup.yml
  when: starbound_backup

- name: Ensure that the universe is restored up if the backup variable is set
  include: restore.yml
  when: starbound_restore

- name: Ensure Starbound is running
  service:
    name: starbound
    state: started
    enabled: true
  become_user: steam
