---

- name: Fail when credentials are not present
  fail: msg="AWS credentials must be defined (starbound_aws_access_key/starbound_aws_secret_key)"
  when: item is undefined
  with_items:
    - "{{ starbound_aws_access_key }}"
    - "{{ starbound_aws_secret_key }}"

- name: Ensure Starbound is stopped
  service:
    name: starbound
    state: stopped
  become_user: steam

- name: Download universe from S3
  s3:
    mode: get
    object: universe.zip
    dest: /home/steam/starbound/storage/universe.zip
    bucket: "{{ backup_s3_bucket }}"
    aws_access_key: "{{ starbound_aws_access_key }}"
    aws_secret_key: "{{ starbound_aws_secret_key }}"

- name: Ensure universe folder is removed
  file:
    path: /home/steam/starbound/storage/universe
    state: absent

- name: Extract the backed up universe
  unarchive:
    copy: no
    src: /home/steam/starbound/storage/universe.zip
    dest: /home/steam/starbound/storage
    owner: steam

- name: Ensure universe archive is removed
  file:
    path: /home/steam/starbound/storage/universe.zip
    state: absent

- name: Ensure Starbound is started
  service:
    name: starbound
    state: started
  become_user: steam
